# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amenj/Projects/Own/diaphony

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amenj/Projects/Own/diaphony

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/jetbrains-toolbox/apps/CLion/ch-0/181.4668.70/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amenj/Projects/Own/diaphony/CMakeFiles /home/amenj/Projects/Own/diaphony/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amenj/Projects/Own/diaphony/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named diaphony

# Build rule for target.
diaphony: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diaphony
.PHONY : diaphony

# fast build rule for target.
diaphony/fast:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/build
.PHONY : diaphony/fast

#=============================================================================
# Target rules for targets named diaphony_test

# Build rule for target.
diaphony_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diaphony_test
.PHONY : diaphony_test

# fast build rule for target.
diaphony_test/fast:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/build
.PHONY : diaphony_test/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/main.cpp.s
.PHONY : main.cpp.s

src/DrawService.o: src/DrawService.cpp.o

.PHONY : src/DrawService.o

# target to build an object file
src/DrawService.cpp.o:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/src/DrawService.cpp.o
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/src/DrawService.cpp.o
.PHONY : src/DrawService.cpp.o

src/DrawService.i: src/DrawService.cpp.i

.PHONY : src/DrawService.i

# target to preprocess a source file
src/DrawService.cpp.i:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/src/DrawService.cpp.i
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/src/DrawService.cpp.i
.PHONY : src/DrawService.cpp.i

src/DrawService.s: src/DrawService.cpp.s

.PHONY : src/DrawService.s

# target to generate assembly for a file
src/DrawService.cpp.s:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/src/DrawService.cpp.s
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/src/DrawService.cpp.s
.PHONY : src/DrawService.cpp.s

src/PointService.o: src/PointService.cpp.o

.PHONY : src/PointService.o

# target to build an object file
src/PointService.cpp.o:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/src/PointService.cpp.o
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/src/PointService.cpp.o
.PHONY : src/PointService.cpp.o

src/PointService.i: src/PointService.cpp.i

.PHONY : src/PointService.i

# target to preprocess a source file
src/PointService.cpp.i:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/src/PointService.cpp.i
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/src/PointService.cpp.i
.PHONY : src/PointService.cpp.i

src/PointService.s: src/PointService.cpp.s

.PHONY : src/PointService.s

# target to generate assembly for a file
src/PointService.cpp.s:
	$(MAKE) -f CMakeFiles/diaphony.dir/build.make CMakeFiles/diaphony.dir/src/PointService.cpp.s
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/src/PointService.cpp.s
.PHONY : src/PointService.cpp.s

test/PointServiceTest.o: test/PointServiceTest.cpp.o

.PHONY : test/PointServiceTest.o

# target to build an object file
test/PointServiceTest.cpp.o:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/PointServiceTest.cpp.o
.PHONY : test/PointServiceTest.cpp.o

test/PointServiceTest.i: test/PointServiceTest.cpp.i

.PHONY : test/PointServiceTest.i

# target to preprocess a source file
test/PointServiceTest.cpp.i:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/PointServiceTest.cpp.i
.PHONY : test/PointServiceTest.cpp.i

test/PointServiceTest.s: test/PointServiceTest.cpp.s

.PHONY : test/PointServiceTest.s

# target to generate assembly for a file
test/PointServiceTest.cpp.s:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/PointServiceTest.cpp.s
.PHONY : test/PointServiceTest.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/point_test.o: test/point_test.cpp.o

.PHONY : test/point_test.o

# target to build an object file
test/point_test.cpp.o:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/point_test.cpp.o
.PHONY : test/point_test.cpp.o

test/point_test.i: test/point_test.cpp.i

.PHONY : test/point_test.i

# target to preprocess a source file
test/point_test.cpp.i:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/point_test.cpp.i
.PHONY : test/point_test.cpp.i

test/point_test.s: test/point_test.cpp.s

.PHONY : test/point_test.s

# target to generate assembly for a file
test/point_test.cpp.s:
	$(MAKE) -f CMakeFiles/diaphony_test.dir/build.make CMakeFiles/diaphony_test.dir/test/point_test.cpp.s
.PHONY : test/point_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... diaphony"
	@echo "... edit_cache"
	@echo "... diaphony_test"
	@echo "... rebuild_cache"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/DrawService.o"
	@echo "... src/DrawService.i"
	@echo "... src/DrawService.s"
	@echo "... src/PointService.o"
	@echo "... src/PointService.i"
	@echo "... src/PointService.s"
	@echo "... test/PointServiceTest.o"
	@echo "... test/PointServiceTest.i"
	@echo "... test/PointServiceTest.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/point_test.o"
	@echo "... test/point_test.i"
	@echo "... test/point_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

